//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadePass.Glazier.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CascadePass.Glazier.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slower, better for complex backgrounds..
        /// </summary>
        public static string AlgorithmDescription_Onyx {
            get {
                return ResourceManager.GetString("AlgorithmDescription_Onyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast, good for simple backgrounds..
        /// </summary>
        public static string AlgorithmDescription_Prism {
            get {
                return ResourceManager.GetString("AlgorithmDescription_Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use machine learning to identify the subject, generate a mask, and make everything else transparent..
        /// </summary>
        public static string AlgorithmMethod_Onyx {
            get {
                return ResourceManager.GetString("AlgorithmMethod_Onyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace a color, usually the most common one, with transparent pixels..
        /// </summary>
        public static string AlgorithmMethod_Prism {
            get {
                return ResourceManager.GetString("AlgorithmMethod_Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind Image Effect.
        /// </summary>
        public static string BehindImageBrush {
            get {
                return ResourceManager.GetString("BehindImageBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshatch.
        /// </summary>
        public static string Brush_Crosshatch {
            get {
                return ResourceManager.GetString("Brush_Crosshatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Translucent Black.
        /// </summary>
        public static string Brush_TranslucentBlack {
            get {
                return ResourceManager.GetString("Brush_TranslucentBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glazier.
        /// </summary>
        public static string Glazier {
            get {
                return ResourceManager.GetString("Glazier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Settings.
        /// </summary>
        public static string Header_ModelSettings {
            get {
                return ResourceManager.GetString("Header_ModelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Settings.
        /// </summary>
        public static string Header_VisualSettings {
            get {
                return ResourceManager.GetString("Header_VisualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Hex {
            get {
                return ResourceManager.GetString("Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Label_Colors {
            get {
                return ResourceManager.GetString("Label_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination (save to) image file.
        /// </summary>
        public static string Label_DestinationFile {
            get {
                return ResourceManager.GetString("Label_DestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Label_Files {
            get {
                return ResourceManager.GetString("Label_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONNX Model File.
        /// </summary>
        public static string Label_ModelFile {
            get {
                return ResourceManager.GetString("Label_ModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Label_OutputSize {
            get {
                return ResourceManager.GetString("Label_OutputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Color.
        /// </summary>
        public static string Label_ReplacementColor {
            get {
                return ResourceManager.GetString("Label_ReplacementColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold.
        /// </summary>
        public static string Label_Similarity {
            get {
                return ResourceManager.GetString("Label_Similarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source image file.
        /// </summary>
        public static string Label_SourceFile {
            get {
                return ResourceManager.GetString("Label_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onyx.
        /// </summary>
        public static string Onyx {
            get {
                return ResourceManager.GetString("Onyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prism.
        /// </summary>
        public static string Prism {
            get {
                return ResourceManager.GetString("Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Windows setting.
        /// </summary>
        public static string Theme_None {
            get {
                return ResourceManager.GetString("Theme_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
    }
}
