name: Build and Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test in Debug Mode
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore src/Glazier.sln 

    - name: Build in Debug mode
      run: dotnet build src/Glazier.sln --configuration Debug

    - name: Run tests
      run: dotnet test src/Glazier.sln --configuration Debug --diag testLog.txt

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults/
